# -*- coding: utf-8 -*-
"""Guess_the_Number_Game_(user).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vdw7K5taTaFMxtcGtl2nxdh6IhVRrDuq?usp=sharing
"""

import random

def guess_num():
  print("Think of a number between 1 and 100.")
  print("I, the computer, will try to guess it!")

  low = 1
  high = 100
  feedback = ""
  attempts = 0

  while feedback != "c":
    guess = random.randint(low, high)
    attempts += 1
    print(f"My guess is {guess}.")

    feedback = input("Is this too high (H), too low (L), or correct (C)? ").lower()

    if feedback == "h":
      high = guess - 1
    elif feedback == "l":
      low = guess + 1
    elif feedback == "c":
      print(f"Yay! I guessed it in {attempts} tries.")
    else:
      print("Invalid input. Please enter H, L, or C.")


guess_num()