# -*- coding: utf-8 -*-
"""Hangman_Python_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nX6kE9J8dE6L1kCb_OlQAn94zLDg-LZZ
"""

import random
import string


words = ["python", "hangman", "challenge", "programming", "kylie", "developer"]

def get_valid_word(words):
    word = random.choice(words)
    while '-' in word or ' ' in word:
        word = random.choice(words)
    return word.upper()

def hangman():
  word = get_valid_word(words)
  word_letters = set(word)
  alphabet = set(string.ascii_uppercase)
  used_letters = set()

  lives = 6

  while len(word_letters) > 0 and lives > 0:
    print('You have', lives, 'lives left and you have used these letters: ', ' '.join(used_letters))

    word_list = [letter if letter in used_letters else '-' for letter in word]
    print('Current word: ', ' '.join(word_list))

    user_guess = input('Guess a letter: ').upper()
    if (user_guess in alphabet - used_letters):
        used_letters.add(user_guess)
        if (user_guess in word_letters):
            word_letters.remove(user_guess)
        else:
          lives -= 1
          print("Letter is not in the word.")
    elif (user_guess in used_letters):
      print("You already used that letter. Try again.")
    else:
      print("Invalid character. Please try again.")

  if (lives == 0):
    print(f"\nYou died, the word was {word}")
  else:
    print(f"\nYAY! You guessed the word {word}!!")

hangman()