# -*- coding: utf-8 -*-
"""06_get_last_element.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mUkm1IDYR_H8oC3OjbD9a4m-8tY0y_2k?usp=sharing
"""

# Pehla element lene ka function
def get_first_element(lst):
  print(lst[-1]) # List ka Last element print karega


# User se list lene ka function
def get_list():
  lst = [] # Khali list banayenge
  userValue = input("Please enter an element of the list or press enter to stop. ")
  while userValue != "": # Jab tak user enter na dabaye, values list me add hoti rahengi
    lst.append(userValue)
    userValue = input("Please enter an element of the list or press enter to stop. ")
  return lst # Puri list return karega

# Main function jo sab kuch control karega
def main():
  lst = get_list()
  get_first_element(lst)



if __name__ == '__main__':
    main()