# -*- coding: utf-8 -*-
"""07_get_list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oaul1Xgtpv55wY0dahC8f49ONa_WIzjq?usp=sharing
"""

CBLUE = '\33[34m'
CWHITE = '\33[37m'

def main():
    lst = []

    value = input(f"Enter a value: {CBLUE}")

    while value:
      value = input(f"{CWHITE}Enter a value: {CBLUE}")
      lst.append(value)
    print(f"{CWHITE}Here's the list: {lst}")

if __name__ == '__main__':
    main()