# -*- coding: utf-8 -*-
"""01_greetings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fH09J2oUwdMCUBEEFIbMLgpyaxxY4nxa
"""

bold_italic = "\033[1;3m"
reset = "\033[0m"

def greet(name):
  return f"{reset}Greetings {name}!"

def main():
    name = input(f"What's your name? {bold_italic}")
    print(greet(name))



if __name__ == '__main__':
    main()