# -*- coding: utf-8 -*-
"""02_in_range.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/196PDGMqvzsKwbt3MIJ22yhttsjBkXcfv
"""

def in_range(n, low, high):
  if (n >= low and n <= high):
	  return True
  else:
	  return False


def main():
    n = int(input("Enter a number: "))
    low = int(input("Enter low number: "))
    hight = int(input("Enter hight number: "))
    print(in_range(n, low, hight))


if __name__ == '__main__':
    main()