# -*- coding: utf-8 -*-
"""05_subtract_7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v49Ae5lHJPVnyGDNnayYgM2jHnguU6k_?usp=sharing
"""

def subtract_seven(num):
  return num - 7


def main():
  num = int(input("Enter a number: "))
  result = subtract_seven(num)
  print("this should be zero:", result)




if __name__ == '__main__':
    main()