# -*- coding: utf-8 -*-
"""01_print_events.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11V0efoE5K571U-BePIsIwsJjvXpLWqnu?usp=sharing
"""

def even_numbers():

    for  i in range(20):
      print(f"{i*2}")




if __name__ == '__main__':
    even_numbers()