# -*- coding: utf-8 -*-
"""Guess_the_Number_Game_(computer).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aI9zAZ22s5C2zeUhjVorgGGvGxi3Qx-v
"""

import random

def guess_the_num():
  print("Welcome to 'Guess the Number' game!")
  print("I'm thinking of a number between 1 and 100...")

  number = random.randint(1, 100)
  guess = None
  attempts = 0

  while guess != number:
    try:
      guess = int(input("Take a guess: "))
      attempts += 1

      if(guess < number):
        print("Too low! Try again.")
      elif(guess > number):
        print("Too high! Try again.")
      else:
        print(f"Congratulations! You guessed the number {number} in {attempts} attempts.")
    except ValueError:
      print("Please enter a valid number.")

guess_the_num()