# -*- coding: utf-8 -*-
"""Password Generator Python Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14iyRnQyImSZm98AyXJ2iO6BHJQzCxfph
"""

import random
import string

def generate_password():
  letters = string.ascii_letters
  digits = string.digits
  special_chars = string.punctuation

  alphabet = letters + digits + special_chars

  num_passwords = int(input("Enter the number of passwords to generate: "))
  length = int(input("Enter the length of each password: "))

  print("\nGenerated Passwords:\n")
  for i in range(num_passwords):
    password = "".join(random.sample(alphabet, length))
    print(f"{i+1}: {password}")

generate_password()