# -*- coding: utf-8 -*-
"""Countdown_Timer_Python_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M2TD3OVDKLrorTJZ675IfnXX-IIStfNi
"""

import time

def countdown_time():
  minutes = int(input("Enter the number of minutes: "))
  seconds = int(input("Enter the number of seconds: "))
  total_seconds = minutes * 60 * seconds

  while total_seconds > 0:
    mins, secs = divmod(total_seconds, 60)
    timeformat = '{:02d}:{:02d}'.format(mins, secs)
    print(timeformat, end='\r')
    time.sleep(1)
    total_seconds -= 1

    print("Time's up!")

countdown_time()