# -*- coding: utf-8 -*-
"""07_Weather_Program.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WVxXwjqxb0wEzm_esaYBOGqax6WDWKZV
"""

!pip install requests

import requests


# my_account_api
api_key = "3500aa8ab775cb0cb97ead2b9fc41866"

# user_input_location
location = input("Enter your city or location: ")

# weather_api
url = f"http://api.openweathermap.org/data/2.5/weather?q={location}&appid={api_key}&units=metric"

response = requests.get(url)
data = response.json()

if(data["cod"] == 200):
  city = data["name"]
  temp = data["main"]["temp"]
  desc = data["weather"][0]["description"]
  humidity = data["main"]["humidity"]
  wind_speed = data["wind"]["speed"]

  print(f"\nWeather Details for {city}:")
  print(f"Temperature: {temp}°C")
  print(f"Condition: {desc}")
  print(f"Humidity: {humidity}%")
  print(f"Wind Speed: {wind_speed} m/s")
else:
  print("Location not found. Please check the name and try again.")