# -*- coding: utf-8 -*-
"""Rock_paper_scissors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eiv-qLznCh4EFdJHp1hGNqMl5FCjC3A0?usp=sharing
"""

import random

def play():
  user = input("Choose rock, paper, or scissors: ").lower()

  computer = random.choice(['rock', 'paper', 'scissors'])

  print(f"\nYou chose {user}, computer chose {computer}.")

  if(user == computer):
    return "It's a tie!"

  if(is_win(user, computer)):
    return "You won!"

  return "You lost!"

def is_win(player, opponent):
  if(player == 'rock' and opponent == 'scissors') or (player == 'paper' and opponent == 'rock') or (player == 'scissors' and opponent == 'paper'):
    return True

while True:
  print(play())
  play_again = input("\nDo you want to play again? (y/n): ").lower()
  if(play_again != 'y'):
    break