# -*- coding: utf-8 -*-
"""06_Bulk_File_Re-namer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D0_yeH4K5UaqACe6M_ugAmvef53IXA3j
"""

from google.colab import drive
import os

def bulk_rename(folder_path, prefix="File", start_number=1):
    try:

        if not os.path.exists(folder_path):
            print("Error: Folder does not exist. Please provide a valid path.")
            return


        files = os.listdir(folder_path)


        for count, filename in enumerate(files, start=start_number):
            old_path = os.path.join(folder_path, filename)

            if os.path.isfile(old_path):
                file_extension = os.path.splitext(filename)[1]
                new_filename = f"{prefix}_{count}{file_extension}"
                new_path = os.path.join(folder_path, new_filename)

                os.rename(old_path, new_path)
                print(f"'{filename}' ➝ '{new_filename}'")

        print("\n✅ All files have been renamed successfully!")

    except Exception as e:
        print(f"❌ Error: {e}")


folder_path = "/content/drive/My Drive/TestFolder"
bulk_rename(folder_path, prefix="MyFile", start_number=1)