# -*- coding: utf-8 -*-
"""04_liftoff.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VvYdrHwhtlTaVGizQkD4q8kJh1uGJ6ek?usp=sharing
"""

def main():
    for i in range(10, 0, -1):
      print(i, end=" ")
    print("Liftoff!")



if __name__ == '__main__':
    main()