# -*- coding: utf-8 -*-
"""05_double_it.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17dnG5OSXsGa_2BxaJFwQTLW1gCB6ssuo?usp=sharing
"""

def main():

    curr_value = int(input("Enter a number: "))

    while curr_value < 100:
      curr_value *= 2
      print(curr_value, end=" ")



if __name__ == '__main__':
    main()