# -*- coding: utf-8 -*-
"""07_print_divisor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NtdftXJ-_wa_cQ4omvYKQw-oJyUUd_Zb?usp=sharing
"""

CBLUE = '\33[34m'
CWHITE = '\33[37m'

def print_divisors(num):
    for i in range(1, num + 1):
        if num % i == 0:
            print(i)


def main():

    num = int(input(f"Enter a number: {CBLUE}"))
    print(f"{CWHITE}The divisors of", num, "are:")
    print_divisors(num)



if __name__ == '__main__':
    main()